image: ubuntu:latest

before_script:
  - apt update
  - DEBIAN_FRONTEND=noninteractive apt install git lib32z1 intltool autoconf automake autopoint bison build-essential flex gawk gettext gperf libtool pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev texinfo python-docutils -y

build:
  script:
    - cd toolchain
    - ./build_toolchain.sh
    - cd ../trunk
    - ./build_firmware.sh
